import 'package:serverpod/serverpod.dart';

// Assuming UserModel is generated by Serverpod from user.spy.yaml
class UserEndpoint extends Endpoint {
  Future<String> hello(Session session, String name) async {
    session.log('Greeting user: $name');
    return 'Hello, $name!';
  }

  Future<bool> updateStatus(Session session, int userId, String newStatus) async {
    // Authenticate session
    final authInfo = await session.authenticated;
    if (authInfo == null) {
      throw EndpointException(message: 'Unauthorized call');
    }

    // Example ORM update query
    session.log('User $userId updated status to $newStatus');
    return true;
  }
}

class EndpointException implements Exception {
  final String message;
  EndpointException({required this.message});
}
